# Generated by Django 3.2.7 on 2021-09-25 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Course',
            fields=[
                ('School', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('progress', models.CharField(max_length=2)),
                ('Date', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resume_Udemy',
        ),
    ]
