# Generated by Django 3.2.7 on 2021-09-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210925_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_course',
            name='progress',
            field=models.CharField(max_length=3),
        ),
    ]
